-- =============================================================
-- CLEANUP GLOBAL
-- A executer sur GLPI_GLOBAL AVANT les nouveaux fichiers
-- =============================================================

DROP VIEW V_ALL_USERS;
DROP VIEW V_ALL_COMPUTERS;
DROP VIEW V_ALL_TICKETS;
DROP VIEW V_ALL_EQUIPEMENTS;
DROP VIEW V_ALL_HISTO;
DROP VIEW V_DASHBOARD_GLOBAL;

DROP DATABASE LINK cergy_link;
DROP DATABASE LINK pau_link;

DROP TABLE SITES CASCADE CONSTRAINTS PURGE;
DROP TABLE ROLES CASCADE CONSTRAINTS PURGE;

COMMIT;
