CREATE DATABASE LINK cergy_link
CONNECT TO glpi_cergy IDENTIFIED BY glpi123
USING '(DESCRIPTION=
  (ADDRESS=(PROTOCOL=TCP)(HOST=127.0.0.1)(PORT=1521))
  (CONNECT_DATA=(SERVICE_NAME=xepdb1))
)';
CREATE DATABASE LINK pau_link
CONNECT TO glpi_pau IDENTIFIED BY glpi123
USING '(DESCRIPTION=
  (ADDRESS=(PROTOCOL=TCP)(HOST=127.0.0.1)(PORT=1521))
  (CONNECT_DATA=(SERVICE_NAME=xepdb1))
)';