CREATE OR REPLACE PROCEDURE refresh_all_mviews
IS
BEGIN
    DBMS_MVIEW.REFRESH('MV_DASHBOARD_GLOBAL', 'C');
    DBMS_OUTPUT.PUT_LINE('MV_DASHBOARD_GLOBAL rafraichie');

    DBMS_MVIEW.REFRESH('MV_STATS_TICKETS', 'C');
    DBMS_OUTPUT.PUT_LINE('MV_STATS_TICKETS rafraichie');

    DBMS_MVIEW.REFRESH('MV_PARC_ACTIF', 'C');
    DBMS_OUTPUT.PUT_LINE('MV_PARC_ACTIF rafraichie');

    DBMS_OUTPUT.PUT_LINE('=== Toutes les MV rafraichies ===');
END;
/